services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8050
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    depends_on:
      - redis
    networks:
        - app_nw

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Optional: for hot-reloading during development
      - /app/node_modules

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
        - app_nw

networks:
  app_nw:
    driver: bridge
