# Generated by Django 5.1.1 on 2024-11-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradesync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="usn",
            field=models.CharField(default="-", max_length=10, null=True),
        ),
    ]
