# Generated by Django 5.1.1 on 2024-10-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradesync", "0002_alter_user_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="acive",
            new_name="active",
        ),
        migrations.AlterField(
            model_name="student",
            name="cgpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="student",
            name="usn",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
