# Generated by Django 5.1.1 on 2025-01-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradesync", "0002_alter_studentperformance_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectmetrics",
            name="highest_scorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highest_scorer",
                to="gradesync.student",
            ),
        ),
    ]
