# Generated by Django 5.1.1 on 2025-01-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradesync", "0003_subjectmetrics_highest_scorer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemesterMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_sgpa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("total_backlogs", models.IntegerField(default=0)),
                (
                    "pass_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fail_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("pass_count", models.IntegerField(default=0)),
                ("fail_1_sub", models.IntegerField(default=0)),
                ("fail_2_subs", models.IntegerField(default=0)),
                ("fail_3_subs", models.IntegerField(default=0)),
                ("fail_greater_3_subs", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradesync.section",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradesync.semester",
                    ),
                ),
            ],
        ),
    ]
