# Generated by Django 5.1.1 on 2024-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradesync", "0003_rename_acive_student_active_alter_student_cgpa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
