# Generated by Django 5.1.1 on 2025-01-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradesync", "0004_semestermetrics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="semester",
            old_name="sem_number",
            new_name="semester_number",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="sem",
            new_name="semester",
        ),
        migrations.AddField(
            model_name="studentperformance",
            name="num_backlogs",
            field=models.IntegerField(default=0),
        ),
    ]
